spring.application.name=tamilan_school
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=tamilan_school;trustServerCertificate=true
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=kaashiv
spring.datasource.password=123
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update